all:
  children:
    aoscx:
      vars:
        ansible_connection: network_cli
        ansible_network_os: arubanetworks.aoscx.aoscx
        ansible_user: tberno-admin
        ansible_command_timeout: 300
      hosts:
        furnace-core:
          ansible_host: 10.20.99.1
          switch_model: 6300m
          image_file: ArubaOS-CX_6400-6300_10_13_1160.swi
        garage-ac:
          ansible_host: 10.20.99.2
          switch_model: 6100
          image_file: ArubaOS-CX_6100-6000_10_13_1161.swi
        office-acc:
          ansible_host: 10.20.99.3
          switch_model: 6100
          image_file: ArubaOS-CX_6100-6000_10_13_1161.swi
