---
- name: Copy Aruba images to secondary
  hosts: aoscx
  gather_facts: no

  tasks:
    - name: Copy image to secondary
      arubanetworks.aoscx.aoscx_command:
        commands:
          - "copy scp://{{ image_server_user }}@{{ image_server_host }}{{ image_server_base_path }}/{{ image_file }} secondary vrf default"
      register: copy_result

    - name: Show copy result
      ansible.builtin.debug:
        var: copy_result.stdout_lines

    - name: Show images after copy
      arubanetworks.aoscx.aoscx_command:
        commands:
          - show images
      register: images_after

    - name: Print images after copy
      ansible.builtin.debug:
        var: images_after.stdout_lines
